run_time_config:
  symbol_list:
    btcusdt:
      quit: true
      keep_run: true
      buy_min_quoter_amount: 20.0
      increasing_price_rate: 0.01
      period: "5min"
    ethusdt:
      quit: true
      keep_run: true
      buy_min_quoter_amount: 20.0
      increasing_price_rate: 0.01
      period: "5min"

