run_time_config:
  symbol_list:
    btcusdt:
      quit: false
      keep_run: true
      buy_min_quoter_amount: 6.0
      increasing_price_rate: 0.01
      period: "5min"
    ethusdt:
      quit: false
      keep_run: true
      buy_min_quoter_amount: 6.0
      increasing_price_rate: 0.01
      period: "5min"
    htusdt:
      quit: false
      keep_run: true
      buy_min_quoter_amount: 6.0
      increasing_price_rate: 0.01
      period: "5min"
    dotusdt:
      quit: false
      keep_run: true
      buy_min_quoter_amount: 6.0
      increasing_price_rate: 0.01
      period: "5min"
    uniusdt:
      quit: false
      keep_run: true
      buy_min_quoter_amount: 6.0
      increasing_price_rate: 0.01
      period: "5min"

