run_time_config:
  symbol_list:
    btcusdt:
      keep_run: true
      buy_min_quoter_amount: 6.0
      increasing_price_rate: 0.01
    ethusdt:
      keep_run: false
      buy_min_quoter_amount: 7.0
      increasing_price_rate: 0.01

