run_time_config:
  symbol_list:
    btcusdt:
      quit: false
      keep_run: true
      buy_min_quoter_amount: 6.0
      increasing_price_rate: 0.01
    ethusdt:
      quit: false
      keep_run: true
      buy_min_quoter_amount: 6.0
      increasing_price_rate: 0.01

